name: GCP Cloud Run
on:
  push:
    branches:
    - main
    paths:
    - api/**

jobs:
  deploy-2-gcr:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: google-github-actions/auth@v0
        name: gcloud auth
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - uses: 'google-github-actions/setup-gcloud@v0'
        name: gcloud sdk set up
      
      - name: Build and Publish
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCR_SERVICE }}

      - uses: 'google-github-actions/deploy-cloudrun@v0'
        name: deploy to cloud run
        with:
          service: ${{ secrets.GCR_SERVICE }}
          image: gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCR_SERVICE }}
      


      
