name: GCP Storage Upload
on:
  push:
    branches:
    - main

jobs:
  upload-2-gcs:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: google-github-actions/auth@v0
        name: gcloud auth
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - uses: google-github-actions/upload-cloud-storage@v0
        name: upload files
        with:
          path: 'public/'
          destination: '${{ secrets.GCS_BUCKET }}'
          parent: false



